package gui;

import gui.audio.AudioSteganography;
import gui.document.DocumentSteganography;
import gui.image.ImageSteganography;
import gui.stegano.Steganography;
import gui.video.VideoSteganography;

/**
 *
 * @author Himanshu Sajwan.
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ImageSteganographyButton = new javax.swing.JButton();
        AudioSteganographyButton = new javax.swing.JButton();
        VideoSteganographyButton = new javax.swing.JButton();
        DocumentSteganographyButton = new javax.swing.JButton();
        SteganographyButton = new javax.swing.JButton();
        backgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setLayout(null);

        ImageSteganographyButton.setBackground(new java.awt.Color(51, 102, 0));
        ImageSteganographyButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        ImageSteganographyButton.setForeground(new java.awt.Color(255, 255, 255));
        ImageSteganographyButton.setText("Image Steganography");
        ImageSteganographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageSteganographyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ImageSteganographyButton);
        ImageSteganographyButton.setBounds(90, 280, 260, 60);

        AudioSteganographyButton.setBackground(new java.awt.Color(153, 0, 153));
        AudioSteganographyButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        AudioSteganographyButton.setForeground(new java.awt.Color(255, 255, 255));
        AudioSteganographyButton.setText("Audio Steganography");
        AudioSteganographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioSteganographyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(AudioSteganographyButton);
        AudioSteganographyButton.setBounds(90, 180, 260, 60);

        VideoSteganographyButton.setBackground(new java.awt.Color(51, 51, 255));
        VideoSteganographyButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        VideoSteganographyButton.setForeground(new java.awt.Color(255, 255, 255));
        VideoSteganographyButton.setText("Video Steganography");
        VideoSteganographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoSteganographyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(VideoSteganographyButton);
        VideoSteganographyButton.setBounds(90, 370, 260, 60);

        DocumentSteganographyButton.setBackground(new java.awt.Color(0, 51, 51));
        DocumentSteganographyButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        DocumentSteganographyButton.setForeground(new java.awt.Color(255, 255, 255));
        DocumentSteganographyButton.setText("Document Steganography");
        DocumentSteganographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentSteganographyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(DocumentSteganographyButton);
        DocumentSteganographyButton.setBounds(90, 470, 260, 60);

        SteganographyButton.setBackground(new java.awt.Color(204, 0, 0));
        SteganographyButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        SteganographyButton.setForeground(new java.awt.Color(255, 255, 255));
        SteganographyButton.setText("Steganography");
        SteganographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SteganographyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SteganographyButton);
        SteganographyButton.setBounds(90, 80, 260, 60);

        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/data/image/Dark_Green_01.jpg"))); // NOI18N
        MainPanel.add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, 0, 450, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ImageSteganographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageSteganographyButtonActionPerformed

        this.setVisible(false);
        
        new ImageSteganography().setVisible(true);
        
    }//GEN-LAST:event_ImageSteganographyButtonActionPerformed

    private void SteganographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SteganographyButtonActionPerformed

        this.setVisible(false);
        
        new Steganography().setVisible(true);
        
    }//GEN-LAST:event_SteganographyButtonActionPerformed

    private void AudioSteganographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioSteganographyButtonActionPerformed

        this.setVisible(false);
        
        new AudioSteganography().setVisible(true);
        
    }//GEN-LAST:event_AudioSteganographyButtonActionPerformed

    private void VideoSteganographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoSteganographyButtonActionPerformed

        this.setVisible(false);

        new VideoSteganography().setVisible(true);
        
    }//GEN-LAST:event_VideoSteganographyButtonActionPerformed

    private void DocumentSteganographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentSteganographyButtonActionPerformed

        this.setVisible(false);

        new DocumentSteganography().setVisible(true);
       
    }//GEN-LAST:event_DocumentSteganographyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AudioSteganographyButton;
    private javax.swing.JButton DocumentSteganographyButton;
    private javax.swing.JButton ImageSteganographyButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SteganographyButton;
    private javax.swing.JButton VideoSteganographyButton;
    private javax.swing.JLabel backgroundImageLabel;
    // End of variables declaration//GEN-END:variables
}
