package gui.stegano;

import gui.Main;
import gui.util.FileDropHandler;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import steganography.core.exceptions.InsufficientBitsException;
import steganography.core.exceptions.InsufficientMemoryException;
import steganography.core.exceptions.InvalidKeyException;
import steganography.core.exceptions.UnsupportedFileException;
import static steganography.core.util.Files.setImageFileExtension;

/**
 *
 * @author Himanshu Sajwan.
 */
public class Steganography extends javax.swing.JFrame {

    protected File COVER_FILE;
    protected File DATA_FILE;
    protected File DESTINATION_FILE;
    
    protected int KEY;
    protected int OFFSET;
    protected int BUFFER_CAPACITY;
  
    private FileDropHandler fd_Cover, fd_Data, fd_Destination;
    
    /**
     * Creates new form ImageSteganography
     */
    public Steganography() {
        initComponents();
        
        fd_Cover = new FileDropHandler();
        fd_Data = new FileDropHandler();
        fd_Destination = new FileDropHandler();
                
        enableDragAndDrop();
        
        reset();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        DestinationButton = new javax.swing.JButton();
        Cover_SourceFileButton = new javax.swing.JButton();
        DestinationLabel = new javax.swing.JLabel();
        DataFilePath = new javax.swing.JLabel();
        DataFileButton = new javax.swing.JButton();
        DataFileLabel = new javax.swing.JLabel();
        DecodeButton = new javax.swing.JButton();
        EncodeButton = new javax.swing.JButton();
        KeyButton = new javax.swing.JButton();
        BuffersSizeButton = new javax.swing.JButton();
        OffsetButton = new javax.swing.JButton();
        BufferSizeLabel = new javax.swing.JLabel();
        Cover_SourceFileLabel = new javax.swing.JLabel();
        DestinationPath = new javax.swing.JLabel();
        CoverFilePath = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        OffsetLabel = new javax.swing.JLabel();
        KeyLabel = new javax.swing.JLabel();
        ShowHideKeyToggleButton = new javax.swing.JToggleButton();
        backgroundImageLabel = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        CoverFileMenuItem = new javax.swing.JMenuItem();
        DataFileMenuItem = new javax.swing.JMenuItem();
        DestinationMenuItem = new javax.swing.JMenuItem();
        EncodeMenuItem = new javax.swing.JMenuItem();
        DecodeMenuItem = new javax.swing.JMenuItem();
        BufferSizeMenu = new javax.swing.JMenu();
        KeyMenuItem = new javax.swing.JMenuItem();
        OffsetMenuItem = new javax.swing.JMenuItem();
        BufferSizeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setLayout(null);

        DestinationButton.setBackground(new java.awt.Color(0, 51, 51));
        DestinationButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        DestinationButton.setForeground(new java.awt.Color(255, 255, 255));
        DestinationButton.setText("Destination");
        DestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationButtonActionPerformed(evt);
            }
        });
        MainPanel.add(DestinationButton);
        DestinationButton.setBounds(460, 160, 130, 30);

        Cover_SourceFileButton.setBackground(new java.awt.Color(0, 106, 164));
        Cover_SourceFileButton.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        Cover_SourceFileButton.setForeground(new java.awt.Color(255, 255, 255));
        Cover_SourceFileButton.setText("Cover / Source");
        Cover_SourceFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cover_SourceFileButtonActionPerformed(evt);
            }
        });
        MainPanel.add(Cover_SourceFileButton);
        Cover_SourceFileButton.setBounds(460, 40, 130, 30);

        DestinationLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        DestinationLabel.setText("Destination:");
        DestinationLabel.setToolTipText("Location where Encoded or Decoded File will be saved.");
        MainPanel.add(DestinationLabel);
        DestinationLabel.setBounds(20, 160, 80, 30);

        DataFilePath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DataFilePath.setText("--------------------------------------------------------------------");
        DataFilePath.setToolTipText("Location that contain Data File.");
        DataFilePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataFilePathMouseEntered(evt);
            }
        });
        MainPanel.add(DataFilePath);
        DataFilePath.setBounds(110, 100, 350, 30);

        DataFileButton.setBackground(new java.awt.Color(102, 0, 0));
        DataFileButton.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        DataFileButton.setForeground(new java.awt.Color(255, 255, 255));
        DataFileButton.setText("Data");
        DataFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataFileButtonActionPerformed(evt);
            }
        });
        MainPanel.add(DataFileButton);
        DataFileButton.setBounds(460, 100, 130, 30);

        DataFileLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        DataFileLabel.setText("Data File:");
        DataFileLabel.setToolTipText("Location that contain Data File.");
        MainPanel.add(DataFileLabel);
        DataFileLabel.setBounds(20, 100, 80, 30);

        DecodeButton.setBackground(new java.awt.Color(0, 102, 0));
        DecodeButton.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        DecodeButton.setForeground(new java.awt.Color(255, 255, 255));
        DecodeButton.setText("Decode");
        DecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecodeButtonActionPerformed(evt);
            }
        });
        MainPanel.add(DecodeButton);
        DecodeButton.setBounds(350, 440, 210, 70);

        EncodeButton.setBackground(new java.awt.Color(0, 0, 104));
        EncodeButton.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        EncodeButton.setForeground(new java.awt.Color(255, 255, 255));
        EncodeButton.setText("Encode");
        EncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncodeButtonActionPerformed(evt);
            }
        });
        MainPanel.add(EncodeButton);
        EncodeButton.setBounds(40, 440, 210, 70);

        KeyButton.setBackground(new java.awt.Color(153, 153, 255));
        KeyButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        KeyButton.setForeground(new java.awt.Color(255, 255, 255));
        KeyButton.setText("Key");
        KeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyButtonActionPerformed(evt);
            }
        });
        MainPanel.add(KeyButton);
        KeyButton.setBounds(40, 350, 100, 40);

        BuffersSizeButton.setBackground(new java.awt.Color(0, 153, 153));
        BuffersSizeButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        BuffersSizeButton.setForeground(new java.awt.Color(255, 255, 255));
        BuffersSizeButton.setText("Buffer Size");
        BuffersSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuffersSizeButtonActionPerformed(evt);
            }
        });
        MainPanel.add(BuffersSizeButton);
        BuffersSizeButton.setBounds(350, 270, 90, 40);

        OffsetButton.setBackground(new java.awt.Color(102, 102, 0));
        OffsetButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        OffsetButton.setForeground(new java.awt.Color(255, 255, 255));
        OffsetButton.setText("Offset");
        OffsetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffsetButtonActionPerformed(evt);
            }
        });
        MainPanel.add(OffsetButton);
        OffsetButton.setBounds(350, 350, 90, 40);

        BufferSizeLabel.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        BufferSizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.add(BufferSizeLabel);
        BufferSizeLabel.setBounds(450, 270, 140, 40);

        Cover_SourceFileLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cover_SourceFileLabel.setText("<HTML>\n<BODY>\n<pre>\nCover / \nSource File:\n</pre>\n</BODY>\n</HTML>");
        Cover_SourceFileLabel.setToolTipText("Location that contain Cover or Source File.");
        MainPanel.add(Cover_SourceFileLabel);
        Cover_SourceFileLabel.setBounds(20, 20, 90, 50);

        DestinationPath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DestinationPath.setText("--------------------------------------------------------------------");
        DestinationPath.setToolTipText("Location where Encoded or Decoded File will be saved.");
        DestinationPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DestinationPathMouseEntered(evt);
            }
        });
        MainPanel.add(DestinationPath);
        DestinationPath.setBounds(110, 160, 350, 30);

        CoverFilePath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CoverFilePath.setText("--------------------------------------------------------------------");
        CoverFilePath.setToolTipText("Location that contain Cover or Source File.");
        CoverFilePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CoverFilePathMouseEntered(evt);
            }
        });
        MainPanel.add(CoverFilePath);
        CoverFilePath.setBounds(110, 40, 350, 30);

        BackButton.setBackground(new java.awt.Color(0, 0, 0));
        BackButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Main Menu");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        MainPanel.add(BackButton);
        BackButton.setBounds(450, 540, 110, 40);

        OffsetLabel.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        OffsetLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.add(OffsetLabel);
        OffsetLabel.setBounds(450, 350, 140, 40);

        KeyLabel.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        KeyLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.add(KeyLabel);
        KeyLabel.setBounds(140, 350, 140, 40);

        ShowHideKeyToggleButton.setBackground(new java.awt.Color(0, 153, 51));
        ShowHideKeyToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowHideKeyToggleButton.setText("Show Key");
        ShowHideKeyToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHideKeyToggleButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ShowHideKeyToggleButton);
        ShowHideKeyToggleButton.setBounds(40, 270, 100, 40);

        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/data/image/Blue_Fog.jpg"))); // NOI18N
        MainPanel.add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, 0, 600, 600);

        FileMenu.setText("File");

        CoverFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CoverFileMenuItem.setText("Cover File");
        CoverFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoverFileMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(CoverFileMenuItem);

        DataFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        DataFileMenuItem.setText("Data File");
        DataFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataFileMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(DataFileMenuItem);

        DestinationMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        DestinationMenuItem.setText("Destination");
        DestinationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(DestinationMenuItem);

        EncodeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        EncodeMenuItem.setText("Encode");
        EncodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncodeMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(EncodeMenuItem);

        DecodeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        DecodeMenuItem.setText("Decode");
        DecodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecodeMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(DecodeMenuItem);

        MainMenuBar.add(FileMenu);

        BufferSizeMenu.setText("Edit");

        KeyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK));
        KeyMenuItem.setText("Key");
        KeyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyMenuItemActionPerformed(evt);
            }
        });
        BufferSizeMenu.add(KeyMenuItem);

        OffsetMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        OffsetMenuItem.setText("Offset");
        OffsetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffsetMenuItemActionPerformed(evt);
            }
        });
        BufferSizeMenu.add(OffsetMenuItem);

        BufferSizeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        BufferSizeMenuItem.setText("Buffer Size");
        BufferSizeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BufferSizeMenuItemActionPerformed(evt);
            }
        });
        BufferSizeMenu.add(BufferSizeMenuItem);

        MainMenuBar.add(BufferSizeMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        Main.mainmenu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CoverFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoverFileMenuItemActionPerformed
       
        openCoverFile();
        
    }//GEN-LAST:event_CoverFileMenuItemActionPerformed

    private void DataFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataFileMenuItemActionPerformed
       
        openDataFile();
        
    }//GEN-LAST:event_DataFileMenuItemActionPerformed

    private void Cover_SourceFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cover_SourceFileButtonActionPerformed
        
        openCoverFile();
        
    }//GEN-LAST:event_Cover_SourceFileButtonActionPerformed

    private void KeyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyMenuItemActionPerformed
      
        readKey();
        
    }//GEN-LAST:event_KeyMenuItemActionPerformed

    private void KeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyButtonActionPerformed

        readKey();
        
    }//GEN-LAST:event_KeyButtonActionPerformed

    private void DataFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataFileButtonActionPerformed

       openDataFile();
        
    }//GEN-LAST:event_DataFileButtonActionPerformed

    private void DestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationButtonActionPerformed

        try {
            setDestination();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_DestinationButtonActionPerformed

    private void DestinationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationMenuItemActionPerformed

        try {
            setDestination();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_DestinationMenuItemActionPerformed

    private void OffsetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffsetButtonActionPerformed

        readOffset();

    }//GEN-LAST:event_OffsetButtonActionPerformed

    private void OffsetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffsetMenuItemActionPerformed

        readOffset();
        
    }//GEN-LAST:event_OffsetMenuItemActionPerformed

    private void ShowHideKeyToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHideKeyToggleButtonActionPerformed
        
        if(ShowHideKeyToggleButton.isSelected()){
            ShowHideKeyToggleButton.setText("Hide Key");
            ShowHideKeyToggleButton.setBackground(new Color(255, 0, 51));
        }
        else{
            ShowHideKeyToggleButton.setText("Show Key");
            ShowHideKeyToggleButton.setBackground(new Color(0, 153, 51));
        }
        printKey();
        
    }//GEN-LAST:event_ShowHideKeyToggleButtonActionPerformed

    private void EncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncodeButtonActionPerformed

        if(encode() == 0){
            reset();
        }
                
    }//GEN-LAST:event_EncodeButtonActionPerformed

    private void DecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecodeButtonActionPerformed
        
        if(decode() == 0){
            reset();
        }
        
    }//GEN-LAST:event_DecodeButtonActionPerformed

    private void EncodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncodeMenuItemActionPerformed

        if(encode() == 0){
            reset();
        }
        
    }//GEN-LAST:event_EncodeMenuItemActionPerformed

    private void BuffersSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuffersSizeButtonActionPerformed

        readBufferCapacity();

    }//GEN-LAST:event_BuffersSizeButtonActionPerformed

    private void BufferSizeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BufferSizeMenuItemActionPerformed

        readBufferCapacity();
        
    }//GEN-LAST:event_BufferSizeMenuItemActionPerformed

    private void DecodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecodeMenuItemActionPerformed

        if (decode() == 0) {
            reset();
        }

    }//GEN-LAST:event_DecodeMenuItemActionPerformed

    private void CoverFilePathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoverFilePathMouseEntered
        if(fd_Cover.isSet()){
            fd_Cover.setDrop(CoverFilePath);
            CoverFilePath.setText(CoverFilePath.getToolTipText());
            COVER_FILE = fd_Cover.getFile();
        }
        
    }//GEN-LAST:event_CoverFilePathMouseEntered

    private void DataFilePathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataFilePathMouseEntered
        if(fd_Data.isSet()){
            fd_Data.setDrop(DataFilePath);
            DataFilePath.setText(DataFilePath.getToolTipText());
            DATA_FILE = fd_Data.getFile();
        }

    }//GEN-LAST:event_DataFilePathMouseEntered

    private void DestinationPathMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DestinationPathMouseEntered
        if(fd_Destination.isSet()){
            fd_Destination.setDrop(DestinationPath);
            DestinationPath.setText(DestinationPath.getToolTipText());
            DESTINATION_FILE = fd_Destination.getFile();
        }
        
    }//GEN-LAST:event_DestinationPathMouseEntered

    protected int encode(){
        
        if(KEY == -1){
            JOptionPane.showMessageDialog(null, "Input a key", "Missing Key", JOptionPane.ERROR_MESSAGE);
            return 1;
        }
        
        if(COVER_FILE == null){
            JOptionPane.showMessageDialog(null, "Input Location for Cover File", "Missing Cover File", JOptionPane.ERROR_MESSAGE);
            return 2;
        }
        
        if(DATA_FILE == null){
            JOptionPane.showMessageDialog(null, "Input Location for Data File", "Missing Data File", JOptionPane.ERROR_MESSAGE);
            return 3;
        }
        
        if(DESTINATION_FILE == null){
            JOptionPane.showMessageDialog(null, "Input Location for Destination File", "Missing Destination File", JOptionPane.ERROR_MESSAGE);
            return 4;
        }
        
        steganography.core.Steganography steg = new steganography.core.Steganography();
        
        if(OFFSET != -1){
            steg.setOffset(OFFSET);
        }
        
        if(BUFFER_CAPACITY != -1){
            steg.setBufferCapacity(BUFFER_CAPACITY);
        }
        
        try {
            steg.encode(COVER_FILE.getPath(), DATA_FILE.getPath(), DESTINATION_FILE.getPath(), KEY);
            
            JOptionPane.showMessageDialog(null, "Successfully Encoded", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            
            return 0;
        } 
        catch (InsufficientMemoryException | IOException | UnsupportedFileException ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Steganography.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        return -1;
    }
    
    protected int decode(){
        
        if(KEY == -1){
            JOptionPane.showMessageDialog(null, "Input a key", "Missing Key", JOptionPane.ERROR_MESSAGE);
            return 1;
        }
        
        if(COVER_FILE == null){
            JOptionPane.showMessageDialog(null, "Input Location for Source File", "Missing Source File", JOptionPane.ERROR_MESSAGE);
            return 2;
        }
        
        if(DESTINATION_FILE == null){
            JOptionPane.showMessageDialog(null, "Input Location for Destination File", "Missing Destination File", JOptionPane.ERROR_MESSAGE);
            return 4;
        }
        
        steganography.core.Steganography steg = new steganography.core.Steganography();
       
        if(OFFSET != -1){
            steg.setOffset(OFFSET);
        }
        
        if(BUFFER_CAPACITY != -1){
            steg.setBufferCapacity(BUFFER_CAPACITY);
        }
        
        try {
            steg.decode(COVER_FILE.getPath(), DESTINATION_FILE.getPath(), KEY);
            JOptionPane.showMessageDialog(null, "Successfully Decoded", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            return 0;
        } 
        catch (UnsupportedFileException | IOException | InsufficientBitsException | InvalidKeyException ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Steganography.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        return -1;
    }
    
    private void readKey() {
        String returnVal;
        do {
            returnVal = JOptionPane.showInputDialog(null, "Input Key", "KEY", JOptionPane.QUESTION_MESSAGE);
            if (returnVal == null) {
                break;
            } else {
                if (!returnVal.isEmpty() && returnVal.matches("^[0-9]*")) {
                    try {
                        int key = Integer.parseInt(returnVal);
                        if (key == 0) {
                            JOptionPane.showMessageDialog(null, "Key cannot be zero!", "Invalid Key!", JOptionPane.WARNING_MESSAGE);
                        } 
                        else {
                            KEY = key;
                            printKey();
                            break;
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Input a key from 1 to " + Integer.MAX_VALUE + " only.", "Input Valid Key", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Input a key from 1 to " + Integer.MAX_VALUE + " only.", "Input Valid Key", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } while (true);
    }
    
    private void readOffset() {
        
        gui.util.ValueSelector value_selector = new gui.util.ValueSelector();
        
        JOptionPane.showMessageDialog(null, value_selector, "Select Offset Size", JOptionPane.PLAIN_MESSAGE);
        
        int result = value_selector.getBASE_VALUE() * value_selector.getMULTIPLIER_VALUE();
        
        if(result >= 0){
            OffsetLabel.setText(result + " Bytes");
            OFFSET = result;
        }
        
    }
    
    private void readBufferCapacity(){
        
        gui.util.ValueSelector value_selector = new gui.util.ValueSelector();
        
        JOptionPane.showMessageDialog(null, value_selector, "Select Buffer Capacity", JOptionPane.PLAIN_MESSAGE);
        
        int result = value_selector.getBASE_VALUE() * value_selector.getMULTIPLIER_VALUE();
        
        if(result >= 0){
            BufferSizeLabel.setText(result + " Bytes");
            BUFFER_CAPACITY = result;
        }
        
    }
    
    
    protected void openCoverFile() {
        JFileChooser chooser = new JFileChooser(".");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Open Cover File.");
        chooser.setAcceptAllFileFilterUsed(true);

        int selection = chooser.showOpenDialog(null);

        if (selection == JFileChooser.APPROVE_OPTION) {
            COVER_FILE = chooser.getSelectedFile();
            if (COVER_FILE.exists()) {
                CoverFilePath.setText(COVER_FILE.getAbsolutePath());
                CoverFilePath.setToolTipText(COVER_FILE.getAbsolutePath());
            } 
            else {
                COVER_FILE = null;
                JOptionPane.showMessageDialog(null, "File does not exists!", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    protected void openDataFile() {
        JFileChooser chooser = new JFileChooser(".");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Open Data File.");
        
        chooser.setAcceptAllFileFilterUsed(true);
        
        int selection = chooser.showOpenDialog(null);

        if (selection == JFileChooser.APPROVE_OPTION) {
            DATA_FILE = chooser.getSelectedFile();
            if (DATA_FILE.exists()) {
                DataFilePath.setText(DATA_FILE.getAbsolutePath());
                DataFilePath.setToolTipText(DATA_FILE.getAbsolutePath());
            } 
            else {
                DATA_FILE = null;
                JOptionPane.showMessageDialog(null, "File does not exists!", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    protected void setDestination() throws IOException {
        JFileChooser chooser = new JFileChooser(".");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Save Encoded File.");
        
        chooser.setAcceptAllFileFilterUsed(false);
        setImageFileExtension(chooser);
        
        int selection = chooser.showSaveDialog(null);

        if (selection == JFileChooser.APPROVE_OPTION) {
            DESTINATION_FILE = chooser.getSelectedFile();
            if (DESTINATION_FILE.exists()) {
                
                int choice = JOptionPane.showConfirmDialog(null, "File already exists. \nDo you want to replace it??", "Confirm Save??", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (choice == JOptionPane.NO_OPTION || choice == JOptionPane.CLOSED_OPTION) {
                    DESTINATION_FILE = null;
                }
                else{
                    DESTINATION_FILE.delete();
                    DESTINATION_FILE.createNewFile();
                    DestinationPath.setText(DESTINATION_FILE.getAbsolutePath());
                    DestinationPath.setToolTipText(DESTINATION_FILE.getAbsolutePath());
                }
            } 
            else {
                DESTINATION_FILE.createNewFile();
                DestinationPath.setText(DESTINATION_FILE.getAbsolutePath());
                DestinationPath.setToolTipText(DESTINATION_FILE.getAbsolutePath());
            }
        }
    }

    private void printKey(){
        
        if(ShowHideKeyToggleButton.isSelected()){
            if(KEY != -1){
                KeyLabel.setText("= " + KEY);
            }
            else{
                KeyLabel.setText(" Key not set");
            }
        }
        else{
            int key = KEY;
            int count = 0;

            while(key > 0){
                count++;
                key /= 10;
            }
            
            char[] hidden_key = new char[count];
            for(int i = 0; i < count; i++){
                hidden_key[i] = '*';
            }
            
            KeyLabel.setText("= " + new String(hidden_key));
            
        }
    }
    
    public final void reset(){
        KEY = -1;
        OFFSET = -1;
        BUFFER_CAPACITY = -1;
        
        COVER_FILE = null;
        DATA_FILE = null;
        DESTINATION_FILE = null;
        CoverFilePath.setText("--------------------------------------------------------------------");
        CoverFilePath.setToolTipText("Location that contain Cover or Source File.");
        
        DataFilePath.setText("--------------------------------------------------------------------");
        DataFilePath.setToolTipText("Location that contain Data File.");
        
        DestinationPath.setText("--------------------------------------------------------------------");
        DestinationPath.setToolTipText("Location where Encoded or Decoded File will be saved.");
        
        KeyLabel.setText("");
        BufferSizeLabel.setText("");
        OffsetLabel.setText("");
        
        if(fd_Cover.isSet()){
            fd_Cover.setSet(false);
        }
        if(fd_Data.isSet()){
            fd_Data.setSet(false);
        }
        if(fd_Destination.isSet()){
            fd_Destination.setSet(false);
        }
        
    }
    
    private void enableDragAndDrop(){
        CoverFilePath.setTransferHandler(fd_Cover);
        DataFilePath.setTransferHandler(fd_Data);
        DestinationPath.setTransferHandler(fd_Destination);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Steganography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Steganography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Steganography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Steganography.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Steganography().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BufferSizeLabel;
    private javax.swing.JMenu BufferSizeMenu;
    private javax.swing.JMenuItem BufferSizeMenuItem;
    private javax.swing.JButton BuffersSizeButton;
    private javax.swing.JMenuItem CoverFileMenuItem;
    public javax.swing.JLabel CoverFilePath;
    private javax.swing.JButton Cover_SourceFileButton;
    private javax.swing.JLabel Cover_SourceFileLabel;
    private javax.swing.JButton DataFileButton;
    private javax.swing.JLabel DataFileLabel;
    private javax.swing.JMenuItem DataFileMenuItem;
    protected javax.swing.JLabel DataFilePath;
    private javax.swing.JButton DecodeButton;
    private javax.swing.JMenuItem DecodeMenuItem;
    private javax.swing.JButton DestinationButton;
    private javax.swing.JLabel DestinationLabel;
    private javax.swing.JMenuItem DestinationMenuItem;
    protected javax.swing.JLabel DestinationPath;
    private javax.swing.JButton EncodeButton;
    private javax.swing.JMenuItem EncodeMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton KeyButton;
    private javax.swing.JLabel KeyLabel;
    private javax.swing.JMenuItem KeyMenuItem;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton OffsetButton;
    private javax.swing.JLabel OffsetLabel;
    private javax.swing.JMenuItem OffsetMenuItem;
    private javax.swing.JToggleButton ShowHideKeyToggleButton;
    private javax.swing.JLabel backgroundImageLabel;
    // End of variables declaration//GEN-END:variables
}
