package gui.util;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static steganography.core.Steganography.GB;
import static steganography.core.Steganography.KB;
import static steganography.core.Steganography.MB;

/** 
 *
 * @author Himanshu Sajwan.
 */
public class ValueSelector extends javax.swing.JPanel {

    private int BASE_VALUE, MULTIPLIER_VALUE;
    
    /**
     * Creates new form VauleSelector
     */
    public ValueSelector() {
        initComponents();
        resetValueReader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BaseValueComboBox = new javax.swing.JComboBox<>();
        MultiplierButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BaseValueLabel = new javax.swing.JLabel();
        MultiplierValueLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BufferCapacityLabel = new javax.swing.JLabel();
        BufferPanel_backgroundImageLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 230));

        BaseValueComboBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BaseValueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Value" }));
        BaseValueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseValueComboBoxActionPerformed(evt);
            }
        });

        MultiplierButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        MultiplierButton.setText("Multiplier");
        MultiplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplierButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Base Value:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Multiplier");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select Capacity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");

        BaseValueLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BaseValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        MultiplierValueLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        MultiplierValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("=");

        BufferCapacityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BufferPanel_backgroundImageLabel.setBackground(new java.awt.Color(0, 204, 51));
        BufferPanel_backgroundImageLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(MultiplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BufferCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BaseValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BaseValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(MultiplierValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BufferPanel_backgroundImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BufferCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(BaseValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(BaseValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(MultiplierValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BufferPanel_backgroundImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BaseValueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseValueComboBoxActionPerformed
        
        ComboBoxItem cb = (ComboBoxItem) BaseValueComboBox.getSelectedItem();
        BASE_VALUE = cb.getValue();
        BaseValueLabel.setText("" + BASE_VALUE);

        long result = ((long)BASE_VALUE * (long)MULTIPLIER_VALUE);

        if(result > Integer.MAX_VALUE){
            BufferCapacityLabel.setText("Value too big!");
        }
        else if(MULTIPLIER_VALUE >= 0){
            BufferCapacityLabel.setText(result + " Bytes");
        }

    }//GEN-LAST:event_BaseValueComboBoxActionPerformed

    private void MultiplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplierButtonActionPerformed
        
        readMultiplier();

        MultiplierValueLabel.setText("" + MULTIPLIER_VALUE);

        long result = ((long)BASE_VALUE * (long)MULTIPLIER_VALUE);

        if(result > Integer.MAX_VALUE){
            BufferCapacityLabel.setText("Value too big!");
        }
        else{
            BufferCapacityLabel.setText(result + " Bytes");
        }

    }//GEN-LAST:event_MultiplierButtonActionPerformed

    public int getBASE_VALUE() {
        return BASE_VALUE;
    }

    public int getMULTIPLIER_VALUE() {
        return MULTIPLIER_VALUE;
    }

    
    
    private void resetValueReader(){
        
        BASE_VALUE = 1;
        MULTIPLIER_VALUE = 1;
        
        Object[] items = new Object[]{new ComboBoxItem("1", 1),
                                    new ComboBoxItem("KB", KB),
                                    new ComboBoxItem("MB", MB),
                                    new ComboBoxItem("GB", GB)
                                    };
        
        DefaultComboBoxModel model = new DefaultComboBoxModel(items);
        BaseValueComboBox.setModel(model);
        
        BaseValueLabel.setText("1");
        MultiplierValueLabel.setText("1");
        
    }

    private void readMultiplier() {
        String returnVal;
        do {
            returnVal = JOptionPane.showInputDialog(null, "Input Multiplier value ", "MULTIPLIER", JOptionPane.QUESTION_MESSAGE);
            if (returnVal == null) {
                break;
            } else {
                if (!returnVal.isEmpty() && returnVal.matches("^[0-9]*")) {
                    try {
                        int multiplier = Integer.parseInt(returnVal);
                        if (multiplier < 0) {
                            JOptionPane.showMessageDialog(null, "Multiplier value cannot be negative!", "Invalid Buffer Size!", JOptionPane.WARNING_MESSAGE);
                        } 
                        else {
                            MULTIPLIER_VALUE = multiplier;
                            break;
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Input Multiplier value from 1 to " + Integer.MAX_VALUE + " only.", "Invalid Buffer Size!", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Input Multiplier value from 1 to " + Integer.MAX_VALUE + " only.", "Invalid Buffer Size!", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } while (true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BaseValueComboBox;
    private javax.swing.JLabel BaseValueLabel;
    private javax.swing.JLabel BufferCapacityLabel;
    private javax.swing.JLabel BufferPanel_backgroundImageLabel;
    private javax.swing.JButton MultiplierButton;
    private javax.swing.JLabel MultiplierValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
